id: IC4A5A44E
legacy_id: P003230
ocr_import_info:
  bdrc_scan_id: W3CN3118
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T22:24:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:18:35.903516+00:00'
last_modified: 2022-09-03 21:21:06.367776
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3118
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3118
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་བརྒྱུད་སྔགས་མཛོད་ནག་འགྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.9354534544396007
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN3134:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3134
      total_pages: 1170
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN3134.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9375179434335797
    legacy_id: v005
  I3CN3133:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3133
      total_pages: 1126
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN3133.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9405749567374961
    legacy_id: v004
  I3CN3132:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3132
      total_pages: 850
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN3132.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9311952500507718
    legacy_id: v003
  I3CN3131:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3131
      total_pages: 1012
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3131.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9322623893025627
    legacy_id: v002
  I3CN3130:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3130
      total_pages: 960
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3130.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.93503938415767
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
